layout_spectrum: 0.5106383
typography_spectrum: 0.5422264
color:
  saturation: 0.6981826
  brandStrength: 0.2995194
  lightness: 0.4787234
  rhythmicContrast: 0.8905905
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: School Networks
